version: '2.1'
services:
  speech_recognizer:
    build: .
    mem_limit: 512m
    mem_reservation: 128M
    environment:
      logger_name: ${logger_name}      
      project: ${project}

    restart: always